
import { Brand, Category, Product, SensorType, NewsItem } from './types';

export const HERO_IMAGE = "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=2564&auto=format&fit=crop";
// Video mẫu cinematic
export const MOCK_VIDEO_URL = "https://www.youtube.com/embed/LXb3EKWsInQ?si=k1t2b3c4d5e6f7g8&autoplay=1&mute=0";

export const NAV_CONFIG = [
  {
    label: 'Máy ảnh',
    category: Category.CAMERA,
    brands: [Brand.SONY, Brand.CANON, Brand.NIKON, Brand.FUJIFILM]
  },
  {
    label: 'Ống kính',
    category: Category.LENS,
    brands: [Brand.SONY, Brand.CANON, Brand.NIKON, Brand.SIGMA, Brand.VILTROX, Brand.CARL_ZEISS]
  },
  {
    label: 'Phụ kiện',
    category: Category.ACCESSORY,
    brands: [Brand.GODOX, Brand.NEEWER, Brand.CANON]
  }
];

export const MOCK_NEWS: NewsItem[] = [
  {
    id: 'n1',
    title: 'Sony A9 III ra mắt: Kỷ nguyên Global Shutter chính thức bắt đầu',
    excerpt: 'Cảm biến Full-frame Global Shutter đầu tiên trên thế giới loại bỏ hoàn toàn hiện tượng rolling shutter, chụp liên tục 120fps.',
    date: '28/05/2025',
    category: 'Công nghệ',
    image: 'https://images.unsplash.com/photo-1516724562728-afc824a36e84?auto=format&fit=crop&q=80&w=1000',
    content: [
      "Sony đã chính thức làm rung chuyển thế giới nhiếp ảnh với việc ra mắt Alpha 9 III, chiếc máy ảnh mirrorless full-frame đầu tiên trên thế giới trang bị cảm biến Global Shutter.",
      "Với công nghệ Global Shutter, A9 III đọc toàn bộ điểm ảnh cùng một lúc thay vì quét từng dòng như cảm biến Rolling Shutter truyền thống. Điều này giúp loại bỏ hoàn toàn hiện tượng méo hình khi chụp chủ thể chuyển động cực nhanh hoặc khi panning máy.",
      "Sức mạnh này cho phép A9 III chụp liên tục 120 khung hình/giây với đầy đủ AF/AE mà không bị chớp đen (blackout). Ngoài ra, tốc độ màn trập tối đa lên tới 1/80.000 giây và khả năng đồng bộ đèn flash ở mọi tốc độ màn trập là những tính năng chưa từng có.",
      "Về khả năng quay phim, máy hỗ trợ 4K 60p (6K oversampling) và 4K 120p không crop, biến nó thành một cỗ máy đa năng cho cả nhiếp ảnh gia thể thao và nhà làm phim chuyên nghiệp."
    ]
  },
  {
    id: 'n2',
    title: 'Canon EOS R1: Flagship tối thượng thách thức mọi giới hạn',
    excerpt: 'Canon chính thức công bố EOS R1 với hệ thống lấy nét Dual Pixel Intelligent AF và khả năng upscale ảnh in-camera.',
    date: '26/05/2025',
    category: 'Ra mắt',
    image: 'https://images.unsplash.com/photo-1519638831568-d9897f54ed69?auto=format&fit=crop&q=80&w=1000',
    content: [
        "Sau nhiều đồn đoán, Canon EOS R1 đã chính thức lộ diện, khẳng định vị thế dẫn đầu trong dòng máy ảnh chuyên nghiệp dành cho phóng viên thể thao và nhiếp ảnh gia thiên nhiên.",
        "Điểm nhấn của R1 là hệ thống lấy nét Dual Pixel Intelligent AF hoàn toàn mới, sử dụng AI để dự đoán chuyển động của cầu thủ, xe đua hay động vật hoang dã với độ chính xác chưa từng có. Tính năng 'Action Priority' tự động nhận diện hành động như sút bóng hay ném rổ để khóa nét vào chủ thể quan trọng nhất.",
        "Dù chỉ sở hữu cảm biến 24MP để tối ưu tốc độ và khả năng xử lý thiếu sáng, R1 được trang bị tính năng Upscaling ngay trong máy (In-camera Upscaling), cho phép tạo ra các tệp ảnh lên tới 96MP với chi tiết sắc nét nhờ thuật toán Deep Learning.",
        "Với thiết kế bền bỉ chuẩn quân đội và khả năng kết nối 5G, EOS R1 sẵn sàng chinh phục Olympic và các sự kiện thể thao lớn nhất hành tinh."
    ]
  },
  {
    id: 'n3',
    title: 'Nikon Z6 III: Bản nâng cấp đáng giá nhất phân khúc tầm trung?',
    excerpt: 'Cảm biến Partially Stacked mới giúp Nikon Z6 III đạt tốc độ lấy nét và chụp ấn tượng, đe dọa vị thế của Sony A7 IV.',
    date: '25/05/2025',
    category: 'Review',
    image: 'https://images.unsplash.com/photo-1500634245200-e5245c7574ef?auto=format&fit=crop&q=80&w=1000',
    content: [
        "Nikon Z6 III đã tạo ra một làn sóng mới trong phân khúc máy ảnh tầm trung nhờ việc trang bị cảm biến Partially Stacked CMOS đầu tiên trên thế giới.",
        "Cảm biến này cho phép tốc độ đọc dữ liệu nhanh hơn 3.5 lần so với Z6 II, mang lại khả năng lấy nét tự động nhanh hơn, chính xác hơn trong điều kiện thiếu sáng (-10 EV) và giảm thiểu rolling shutter khi quay video.",
        "Kính ngắm EVF của Z6 III cũng là điểm sáng với độ sáng lên tới 4000 nits và dải màu DCI-P3, mang lại trải nghiệm ngắm chụp chân thực nhất từ trước đến nay trên dòng máy Nikon.",
        "Với khả năng quay 6K/60p N-RAW ngay trong máy và mức giá cạnh tranh, Z6 III thực sự là một đối thủ đáng gờm."
    ]
  },
  {
      id: 'n4',
      title: 'Fujifilm X-T50: Film Simulation Dial - Sự trở lại của hoài niệm',
      excerpt: 'Lần đầu tiên Fujifilm tích hợp vòng xoay giả lập màu phim ngay trên thân máy, hướng tới người dùng yêu thích sự tiện lợi.',
      date: '24/05/2025',
      category: 'Trên tay',
      image: 'https://images.unsplash.com/photo-1616423664033-6351892fb5f0?auto=format&fit=crop&q=80&w=1000',
      content: [
          "Fujifilm X-T50 mang đến một thiết kế vừa lạ vừa quen. Điểm thay đổi lớn nhất chính là vòng xoay Film Simulation Dial nằm ở vai trái máy, thay thế cho vòng chỉnh Drive Mode truyền thống.",
          "Vòng xoay này cho phép người dùng chuyển đổi nhanh giữa các giả lập màu trứ danh như Classic Chrome, Acros, hay REALA ACE mới nhất mà không cần truy cập vào menu. Đây là một bước đi táo bạo hướng tới người dùng trẻ và những người sáng tạo nội dung cần 'ăn liền'.",
          "Bên trong vẻ ngoài cổ điển là sức mạnh hiện đại với cảm biến 40MP X-Trans CMOS 5 HR và vi xử lý X-Processor 5, thừa hưởng từ đàn anh X-T5, cùng hệ thống chống rung IBIS 7-stop trong một thân máy nhỏ gọn."
      ]
  }
];

export const MOCK_PRODUCTS: Product[] = [
  // --- SONY CAMERAS ---
  {
    id: 's1',
    name: 'Sony ZV-E10 (Body) (Màu trắng)',
    brand: Brand.SONY,
    category: Category.CAMERA,
    price: 13490000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1127/ar/sony-zv-e10-body-white-qua-33.jpg',
    sensor: SensorType.APS_C,
    resolution: '24.2MP',
    releaseYear: 2021,
    description: 'Máy ảnh Vlog chuyên nghiệp Sony ZV-E10 với cảm biến APS-C lớn, mang lại chất lượng hình ảnh điện ảnh và khả năng xóa phông ấn tượng. Tối ưu cho nhà sáng tạo nội dung.',
    features: ['Cảm biến APS-C Exmor CMOS 24.2MP', 'Quay video 4K30p không crop', 'Lấy nét tự động Real-time Eye AF', 'Màn hình xoay lật cảm ứng'],
    isNew: false,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100 - 32000', shutterSpeed: '1/4000 - 30s', focusSystem: '425 điểm pha', videoRes: '4K 30p', weight: '343g', dimensions: '115 x 64 x 45 mm', battery: 'NP-FW50', storage: 'SD/SDHC/SDXC', mount: 'Sony E' }
  },
  {
    id: 's2',
    name: 'Sony ZV-E10 (Body) (Màu đen)',
    brand: Brand.SONY,
    category: Category.CAMERA,
    price: 13490000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1127/ar/zv-e10-qua-4.jpg',
    sensor: SensorType.APS_C,
    resolution: '24.2MP',
    releaseYear: 2021,
    description: 'Chiếc máy ảnh Vlog quốc dân Sony ZV-E10. Nhỏ gọn, mạnh mẽ với khả năng thay đổi ống kính linh hoạt cho chất lượng video chuyên nghiệp.',
    features: ['Micro định hướng 3 capsule', 'Chế độ Product Showcase', 'Livestream trực tiếp', 'S-Log3 và HLG'],
    isBestSeller: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100 - 32000', shutterSpeed: '1/4000 - 30s', focusSystem: '425 điểm pha', videoRes: '4K 30p', weight: '343g', dimensions: '115 x 64 x 45 mm', battery: 'NP-FW50', storage: 'SD/SDHC/SDXC', mount: 'Sony E' }
  },
  {
    id: 's3',
    name: 'Sony a6400 + 18-135mm OSS',
    brand: Brand.SONY,
    category: Category.CAMERA,
    price: 26990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1127/ar/sony-a6400-18-135-qua-update-22.jpg',
    sensor: SensorType.APS_C,
    resolution: '24.2MP',
    releaseYear: 2019,
    description: 'Combo Sony a6400 kèm lens 18-135mm. Tốc độ lấy nét chớp nhoáng 0.02s. Hoàn hảo cho du lịch và nhiếp ảnh đường phố.',
    features: ['Lấy nét siêu tốc 0.02s', 'Real-time Tracking & Eye AF', 'Chụp liên tục 11fps', 'Ống kính 18-135mm đa dụng'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100 - 32000', shutterSpeed: '1/4000 - 30s', focusSystem: '425 điểm pha', videoRes: '4K 30p', weight: '403g', dimensions: '120 x 67 x 60 mm', battery: 'NP-FW50', storage: 'SD/SDHC/SDXC', mount: 'Sony E' }
  },
  {
    id: 's4',
    name: 'Sony a6400 + 18-105mm F4G OSS',
    brand: Brand.SONY,
    category: Category.CAMERA,
    price: 25490000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1127/ar/sony-a6400-kem-18-105-qua-update-22.jpg',
    sensor: SensorType.APS_C,
    resolution: '24.2MP',
    releaseYear: 2019,
    description: 'Combo quay phim tối thượng: Sony a6400 và ống kính G Power Zoom 18-105mm F4. Zoom điện mượt mà, khẩu độ không đổi.',
    features: ['Power Zoom điện tử', 'Khẩu độ F4 toàn dải', 'Quay phim 4K HDR', 'Body hợp kim magie'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100 - 32000', shutterSpeed: '1/4000 - 30s', focusSystem: 'Fast Hybrid AF', videoRes: '4K 30p', weight: '403g', dimensions: '120 x 67 x 60 mm', battery: 'NP-FW50', storage: 'SD/SDHC/SDXC', mount: 'Sony E' }
  },
  {
    id: 's5',
    name: 'Máy Quay Sony FX2',
    brand: Brand.SONY,
    category: Category.CAMERA,
    price: 45990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0909/ar/sony-fx2-qua-2.png',
    sensor: SensorType.APS_C,
    resolution: '26MP',
    releaseYear: 2024,
    description: 'Sony FX2 Cinema Line. Máy quay điện ảnh chuyên nghiệp trong thân hình nhỏ gọn. Cảm biến Back-illuminated mới.',
    features: ['Cảm biến BSI APS-C Cinema', 'Quay 4K 120p 10-bit 4:2:2', 'Màu S-Cinetone', 'Quạt tản nhiệt tích hợp'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: 'Dual Base ISO', shutterSpeed: '1/8000 - 1s', focusSystem: 'Fast Hybrid AF', videoRes: '4K 120p', weight: '562g', dimensions: '130 x 78 x 85 mm', battery: 'NP-FZ100', storage: 'CFexpress A / SD', mount: 'Sony E' }
  },
  {
    id: 's6',
    name: 'Sony FX3a',
    brand: Brand.SONY,
    category: Category.CAMERA,
    price: 92000000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1103/ar/sony-fx3a-qua.png',
    sensor: SensorType.FULL_FRAME,
    resolution: '12.1MP',
    releaseYear: 2024,
    description: 'Sony FX3a - Phiên bản nâng cấp tối ưu hóa cho làm phim. Quay đêm đỉnh cao với ISO mở rộng 409,600.',
    features: ['Cảm biến Full-Frame 12.1MP', 'ISO 409,600', 'Xử lý AI mới nhất', 'Thiết kế lồng (Cage-free)'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '80 - 102400', shutterSpeed: '1/8000 - 30s', focusSystem: '627 điểm pha', videoRes: '4K 120p', weight: '715g', dimensions: '130 x 78 x 85 mm', battery: 'NP-FZ100', storage: 'CFexpress A / SD', mount: 'Sony E' }
  },
  {
    id: 's7',
    name: 'Sony A7 Mark IV',
    brand: Brand.SONY,
    category: Category.CAMERA,
    price: 54990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0908/ar/a7m4-qua-22.jpg',
    sensor: SensorType.FULL_FRAME,
    resolution: '33MP',
    releaseYear: 2021,
    description: 'Chuẩn mực Hybrid Camera mới. Cân bằng hoàn hảo giữa nhiếp ảnh độ phân giải cao 33MP và quay phim 4K 60p.',
    features: ['Cảm biến 33MP Exmor R', 'Quay 4K 60p 10-bit', 'Focus Breathing Comp', 'Real-time Eye AF Bird'],
    isBestSeller: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-51200', shutterSpeed: '1/8000s', focusSystem: '759 điểm pha', videoRes: '4K 60p', weight: '658g', dimensions: '131 x 96 x 80 mm', battery: 'NP-FZ100', storage: 'CFexpress A / SD', mount: 'Sony E' }
  },
  {
    id: 's8',
    name: 'Sony A7C (Bạc) + Tamron 28-75mm G2',
    brand: Brand.SONY,
    category: Category.CAMERA,
    price: 46500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0818/ar/sony-a7c-bac-tamron-2875-g2-qua.png',
    sensor: SensorType.FULL_FRAME,
    resolution: '24.2MP',
    releaseYear: 2020,
    description: 'Combo du lịch hoàn hảo: Body Full-frame nhỏ gọn nhất và lens đa dụng khẩu lớn.',
    features: ['Body Full-frame Compact', 'Chống rung 5 trục', 'Lens F2.8 toàn dải', 'Màu bạc cổ điển'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-51200', shutterSpeed: '1/4000s', focusSystem: '693 điểm pha', videoRes: '4K 30p', weight: '509g', dimensions: '124 x 71 x 60 mm', battery: 'NP-FZ100', storage: 'SD UHS-II', mount: 'Sony E' }
  },
  {
    id: 's9',
    name: 'Sony A6700 + 16-50mm OSS',
    brand: Brand.SONY,
    category: Category.CAMERA,
    price: 36990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1115/ar/sony-a6700-16-50-qua.jpeg',
    sensor: SensorType.APS_C,
    resolution: '26MP',
    releaseYear: 2023,
    description: 'Flagship APS-C thế hệ mới. Chip AI chuyên dụng nhận diện chủ thể và quay 4K 120p.',
    features: ['Vi xử lý AI', 'Cảm biến 26MP BSI', 'Quay 4K 120p', 'Chống rung Active Mode'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-32000', shutterSpeed: '1/4000s', focusSystem: '759 điểm + AI', videoRes: '4K 120p', weight: '493g', dimensions: '122 x 69 x 64 mm', battery: 'NP-FZ100', storage: 'SD UHS-II', mount: 'Sony E' }
  },
  {
    id: 's10',
    name: 'Sony A7 Mark IV + Sigma 24-70mm II',
    brand: Brand.SONY,
    category: Category.CAMERA,
    price: 79990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2024/1116/ar/a7-mark-iv-sigma-24-70mm-f2-8-mark-ii.jpg',
    sensor: SensorType.FULL_FRAME,
    resolution: '33MP',
    releaseYear: 2024,
    description: 'Combo làm nghề đỉnh cao. Body đa năng và lens Art thế hệ 2 sắc nét.',
    features: ['Chất lượng Sigma Art II', 'Khẩu F2.8 xóa phông', 'AF nhanh yên tĩnh', 'Lớp phủ Nano Porous'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-51200', shutterSpeed: '1/8000s', focusSystem: '759 điểm', videoRes: '4K 60p', weight: '658g', dimensions: '131 x 96 x 80 mm', battery: 'NP-FZ100', storage: 'CFexpress A / SD', mount: 'Sony E' }
  },
  // --- CANON CAMERAS ---
  {
    id: 'c1',
    name: 'Canon EOS R8',
    brand: Brand.CANON,
    category: Category.CAMERA,
    price: 31500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2023/0209/ar/canon-r8-1.jpg',
    sensor: SensorType.FULL_FRAME,
    resolution: '24.2MP',
    releaseYear: 2023,
    description: 'Full-frame nhẹ nhất dòng EOS R. Thừa hưởng cảm biến và AF từ R6 Mark II.',
    features: ['Cảm biến 24.2MP', 'Dual Pixel CMOS AF II', 'Quay 4K60p', 'Chụp 40fps'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-102400', shutterSpeed: '1/4000s', focusSystem: 'Dual Pixel II', videoRes: '4K 60p', weight: '461g', dimensions: '132 x 86 x 70 mm', battery: 'LP-E17', storage: 'SD UHS-II', mount: 'Canon RF' }
  },
  {
    id: 'c2',
    name: 'Canon EOS R50V (Body)',
    brand: Brand.CANON,
    category: Category.CAMERA,
    price: 16500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1119/ar/r50v-body-qua-22.jpg',
    sensor: SensorType.APS_C,
    resolution: '24.2MP',
    releaseYear: 2023,
    description: 'Máy ảnh khởi đầu hoàn hảo cho Creator. Nhỏ gọn, dễ sử dụng, chất lượng vượt trội smartphone.',
    features: ['Quay 4K 30p Oversampled', 'Dual Pixel CMOS AF II', 'Quay dọc Vertical Video', 'Live Streaming USB'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-32000', shutterSpeed: '1/4000s', focusSystem: 'Dual Pixel II', videoRes: '4K 30p', weight: '375g', dimensions: '116 x 85 x 68 mm', battery: 'LP-E17', storage: 'SD UHS-I', mount: 'Canon RF' }
  },
  {
    id: 'c3',
    name: 'Canon EOS R6 Mark III + RF 24-105mm F4L',
    brand: Brand.CANON,
    category: Category.CAMERA,
    price: 85900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1106/ar/canon-r6-mark-iii-15.jpg',
    sensor: SensorType.FULL_FRAME,
    resolution: '24.2MP',
    releaseYear: 2024,
    description: 'Ông vua tốc độ thế hệ 3. Lấy nét AI thông minh hơn, quay 6K RAW.',
    features: ['Cảm biến Stacked mới', 'Quay 6K RAW', 'Chống rung 8-stop', 'Lens L-series đa dụng'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-102400', shutterSpeed: '1/8000s', focusSystem: 'Dual Pixel Intelligent AF', videoRes: '6K 60p RAW', weight: '670g', dimensions: '138 x 98 x 88 mm', battery: 'LP-E6NH', storage: '2x SD UHS-II', mount: 'Canon RF' }
  },
  {
    id: 'c4',
    name: 'Canon EOS R10 + Kit RF-S 18-45mm',
    brand: Brand.CANON,
    category: Category.CAMERA,
    price: 21990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1121/ar/canon-r10-kit-qua-22.jpg',
    sensor: SensorType.APS_C,
    resolution: '24.2MP',
    releaseYear: 2022,
    description: 'Hiệu suất cao trong thân máy nhỏ. Tốc độ chụp liên tiếp ấn tượng cho thể thao và động vật.',
    features: ['Chụp 23fps cơ khí', 'Dual Pixel CMOS AF II', 'Quay 4K 60p (crop)', 'Flash cóc tích hợp'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-32000', shutterSpeed: '1/4000s', focusSystem: 'Dual Pixel II', videoRes: '4K 60p', weight: '429g', dimensions: '122 x 87 x 83 mm', battery: 'LP-E17', storage: 'SD UHS-II', mount: 'Canon RF' }
  },
  {
    id: 'c5',
    name: 'Canon EOS R5',
    brand: Brand.CANON,
    category: Category.CAMERA,
    price: 82000000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1119/ar/may-anh-canon-eos-r5-qua-22.jpg',
    sensor: SensorType.FULL_FRAME,
    resolution: '45MP',
    releaseYear: 2020,
    description: 'Định nghĩa lại giới hạn. Siêu phẩm 8K mở ra kỷ nguyên mới về độ phân giải và tốc độ.',
    features: ['Quay video 8K RAW', 'Cảm biến 45MP', 'Chống rung IBIS 8-stop', '1053 điểm AF'],
    isBestSeller: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-51200', shutterSpeed: '1/8000s', focusSystem: 'Dual Pixel II', videoRes: '8K 30p', weight: '738g', dimensions: '138 x 97 x 88 mm', battery: 'LP-E6NH', storage: 'CFexpress B / SD', mount: 'Canon RF' }
  },
  {
    id: 'c6',
    name: 'Canon EOS R1 + Ngàm EF-EOS R',
    brand: Brand.CANON,
    category: Category.CAMERA,
    price: 160000000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2024/1017/ar/canon-r1-kem-ngam-ef-eos-r.png',
    sensor: SensorType.FULL_FRAME,
    resolution: '24MP',
    releaseYear: 2024,
    description: 'Flagship thể thao tối thượng. Hệ thống lấy nét Cross-type AF chưa từng có.',
    features: ['Cross-type AF', 'Chụp 40fps', 'Upscaling 96MP in-camera', 'Kèm ngàm chuyển EF'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-102400', shutterSpeed: '1/64000s', focusSystem: 'Cross-type AF', videoRes: '6K 60p', weight: '920g', dimensions: '157 x 149 x 87 mm', battery: 'LP-E19', storage: '2x CFexpress B', mount: 'Canon RF' }
  },
  {
    id: 'c7',
    name: 'Canon EOS R50V + Lens 14-30mm (Trắng)',
    brand: Brand.CANON,
    category: Category.CAMERA,
    price: 19500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1119/ar/canon-r50v-white-lens-pin-qua-22.jpg',
    sensor: SensorType.APS_C,
    resolution: '24.2MP',
    releaseYear: 2023,
    description: 'Phiên bản màu trắng thời trang kèm lens góc rộng. Tặng thêm pin dự phòng.',
    features: ['Màu trắng tinh tế', 'Lens góc rộng vlog', 'Tặng Pin LP-E17', 'Quay 4K không crop'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-32000', shutterSpeed: '1/4000s', focusSystem: 'Dual Pixel II', videoRes: '4K 30p', weight: '375g', dimensions: '116 x 85 x 68 mm', battery: 'LP-E17', storage: 'SD UHS-I', mount: 'Canon RF' }
  },
  // --- NIKON CAMERAS ---
  {
    id: 'n1',
    name: 'Nikon ZR',
    brand: Brand.NIKON,
    category: Category.CAMERA,
    price: 42000000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0910/ar/nikon-zr-1.jpg',
    sensor: SensorType.FULL_FRAME,
    resolution: '45.7MP',
    releaseYear: 2025,
    description: 'Nikon ZR concept. Sự kết hợp giữa cổ điển và công nghệ tương lai.',
    features: ['Thiết kế Retro', 'Cảm biến Stacked', 'Quay 8K', 'Màn hình xoay lật đa góc'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '64-25600', shutterSpeed: '1/32000s', focusSystem: 'Hybrid AF', videoRes: '8K 30p', weight: '600g', dimensions: '144 x 103 x 49 mm', battery: 'EN-EL15c', storage: 'SD / CFexpress', mount: 'Nikon Z' }
  },
  {
    id: 'n2',
    name: 'Nikon Zf (Bạc)',
    brand: Brand.NIKON,
    category: Category.CAMERA,
    price: 48990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0906/ar/nikon-zf-silver-1.jpg',
    sensor: SensorType.FULL_FRAME,
    resolution: '24.5MP',
    releaseYear: 2023,
    description: 'Biểu tượng phong cách. Thiết kế lấy cảm hứng từ FM2 huyền thoại với công nghệ Z series mới nhất.',
    features: ['Thiết kế Heritage', 'Chế độ B&W chuyên dụng', 'Ổn định hình ảnh 8-stop', 'Pixel Shift 96MP'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-64000', shutterSpeed: '1/8000s', focusSystem: '273 điểm', videoRes: '4K 60p', weight: '710g', dimensions: '144 x 103 x 49 mm', battery: 'EN-EL15c', storage: 'SD + MicroSD', mount: 'Nikon Z' }
  },
  {
    id: 'n3',
    name: 'Nikon Z6 Mark II',
    brand: Brand.NIKON,
    category: Category.CAMERA,
    price: 39500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham-2019/may-anh-moi/nikon-z6-ii/may-anh-nikon-z6-ii-1.jpg',
    sensor: SensorType.FULL_FRAME,
    resolution: '24.5MP',
    releaseYear: 2020,
    description: 'Cân bằng hoàn hảo cho cả chụp và quay. Dual Expeed 6 xử lý mạnh mẽ.',
    features: ['Dual Expeed 6', '2 khe thẻ nhớ', 'Eye-AF cho người và thú', 'Quay 4K 60p'],
    isBestSeller: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-51200', shutterSpeed: '1/8000s', focusSystem: '273 điểm Hybrid', videoRes: '4K 60p', weight: '705g', dimensions: '134 x 100 x 69 mm', battery: 'EN-EL15c', storage: 'CFexpress B + SD', mount: 'Nikon Z' }
  },
  {
    id: 'n4',
    name: 'Nikon Z5 II + Kit 24-50mm',
    brand: Brand.NIKON,
    category: Category.CAMERA,
    price: 32900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0529/ar/z5-ii-qua-4.jpg',
    sensor: SensorType.FULL_FRAME,
    resolution: '24MP',
    releaseYear: 2024,
    description: 'Bản nâng cấp của dòng Z5 entry-level. Lấy nét tốt hơn và quay video cải thiện.',
    features: ['Cảm biến Full-frame giá tốt', 'Kit nhỏ gọn', '2 khe thẻ SD', 'Chống rung 5 trục'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-51200', shutterSpeed: '1/8000s', focusSystem: '273 điểm', videoRes: '4K 30p', weight: '675g', dimensions: '134 x 100 x 69 mm', battery: 'EN-EL15c', storage: '2x SD UHS-II', mount: 'Nikon Z' }
  },
  {
    id: 'n5',
    name: 'Nikon Z7 Mark II',
    brand: Brand.NIKON,
    category: Category.CAMERA,
    price: 59900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2024/0816/ar/nikon-z7-mark-ii.jpg',
    sensor: SensorType.FULL_FRAME,
    resolution: '45.7MP',
    releaseYear: 2020,
    description: 'Chi tiết tuyệt đối. Dành cho nhiếp ảnh phong cảnh và studio cần độ phân giải cao.',
    features: ['Độ phân giải 45.7MP', 'Không bộ lọc low-pass', '493 điểm lấy nét', 'Quay 4K 60p'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '64-25600', shutterSpeed: '1/8000s', focusSystem: '493 điểm', videoRes: '4K 60p', weight: '705g', dimensions: '134 x 100 x 69 mm', battery: 'EN-EL15c', storage: 'CFexpress B + SD', mount: 'Nikon Z' }
  },
  {
    id: 'n6',
    name: 'Nikon Z30 + Kit 16-50mm',
    brand: Brand.NIKON,
    category: Category.CAMERA,
    price: 16500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2022/0630/ar/nikon-z30-9.jpg',
    sensor: SensorType.APS_C,
    resolution: '20.9MP',
    releaseYear: 2022,
    description: 'Thiết kế cho Vlogger. Màn hình xoay lật, quay 4K và micro chất lượng cao.',
    features: ['Chuyên dụng Vlog', 'Quay 4K UHD', 'Rec lamp tally', 'Gọn nhẹ 405g'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-51200', shutterSpeed: '1/4000s', focusSystem: '209 điểm', videoRes: '4K 30p', weight: '405g', dimensions: '128 x 73 x 59 mm', battery: 'EN-EL25', storage: 'SD UHS-I', mount: 'Nikon Z' }
  },
  {
    id: 'n7',
    name: 'Nikon Z fc + Z 28mm f/2.8',
    brand: Brand.NIKON,
    category: Category.CAMERA,
    price: 24500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2021/0702/ar/nikon-z-fc-8.jpg',
    sensor: SensorType.APS_C,
    resolution: '20.9MP',
    releaseYear: 2021,
    description: 'Phong cách cổ điển, tính năng hiện đại. Thân máy lấy cảm hứng từ máy film FM2.',
    features: ['Thiết kế Retro', 'Màn hình xoay lật', 'Eye-AF', 'Kèm lens prime 28mm SE'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-51200', shutterSpeed: '1/4000s', focusSystem: '209 điểm', videoRes: '4K 30p', weight: '445g', dimensions: '134 x 93 x 43 mm', battery: 'EN-EL25', storage: 'SD UHS-I', mount: 'Nikon Z' }
  },
  // --- FUJIFILM CAMERAS ---
  {
    id: 'f1',
    name: 'Fujifilm X-E5',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 25990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1127/ar/fujifilm-xe5-den-qua-22.jpg',
    sensor: SensorType.APS_C,
    resolution: '40MP',
    releaseYear: 2024,
    description: 'Phong cách Rangefinder tối giản. Cảm biến 40MP thế hệ mới trong thân máy siêu gọn.',
    features: ['Cảm biến X-Trans 5 40MP', 'Thiết kế Rangefinder', 'Giả lập màu film', 'Không có IBIS'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '125-12800', shutterSpeed: '1/4000s', focusSystem: 'Hybrid AF', videoRes: '6.2K 30p', weight: '360g', dimensions: '121 x 73 x 33 mm', battery: 'NP-W126S', storage: 'SD UHS-I', mount: 'Fujifilm X' }
  },
  {
    id: 'f2',
    name: 'Fujifilm X-M5 (Body) Đen',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 19500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1127/ar/fujifilm-x-m5-body-den-qua-22.jpg',
    sensor: SensorType.APS_C,
    resolution: '26MP',
    releaseYear: 2024,
    description: 'Dòng X-M trở lại. Tập trung vào quay phim và sáng tạo nội dung mạng xã hội.',
    features: ['Chế độ Vlog', 'Màn hình xoay lật', 'Nhỏ gọn bỏ túi', 'Mic input 3.5mm'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '160-12800', shutterSpeed: '1/32000s (ES)', focusSystem: '425 điểm', videoRes: '4K 60p', weight: '320g', dimensions: '111 x 64 x 38 mm', battery: 'NP-W126S', storage: 'SD UHS-I', mount: 'Fujifilm X' }
  },
  {
    id: 'f3',
    name: 'Fujifilm X-S20',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 29990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2023/0526/ar/fujifilm-x-s20.jpg',
    sensor: SensorType.APS_C,
    resolution: '26.1MP',
    releaseYear: 2023,
    description: 'Chiếc máy ảnh Hybrid tốt nhất tầm giá. Pin trâu, chống rung tốt, màu đẹp.',
    features: ['Pin NP-W235 dung lượng cao', 'Chống rung IBIS 7-stop', 'Vlog Mode', 'Quay 6.2K Open Gate'],
    isBestSeller: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '160-12800', shutterSpeed: '1/4000s', focusSystem: 'AI Subject Detection', videoRes: '6.2K 30p', weight: '491g', dimensions: '127 x 85 x 65 mm', battery: 'NP-W235', storage: 'SD UHS-II', mount: 'Fujifilm X' }
  },
  {
    id: 'f4',
    name: 'Fujifilm X-T5 Kit 16-80mm (Bạc)',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 45500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2022/1115/ar/fujifilm-x-t5.jpg',
    sensor: SensorType.APS_C,
    resolution: '40.2MP',
    releaseYear: 2022,
    description: 'Quay về nhiếp ảnh thuần túy. Độ phân giải cao, 3 vòng xoay điều khiển cổ điển.',
    features: ['Cảm biến 40MP HR', '3 vòng xoay điều khiển', 'Màn hình lật 3 chiều', 'IBIS 7-stop'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '125-12800', shutterSpeed: '1/8000s', focusSystem: 'AI AF', videoRes: '6.2K 30p', weight: '557g', dimensions: '129 x 91 x 63 mm', battery: 'NP-W235', storage: '2x SD UHS-II', mount: 'Fujifilm X' }
  },
  {
    id: 'f5',
    name: 'Fujifilm X-T30 Mark III (Bạc)',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 23900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1121/ar/fujifilm-xt30-iii-body-silver-qua-33.jpg',
    sensor: SensorType.APS_C,
    resolution: '40MP',
    releaseYear: 2024,
    description: 'Tiểu X-T5. Nhỏ gọn nhưng mang sức mạnh của cảm biến 40MP cao cấp.',
    features: ['Cảm biến 40MP', 'Nhỏ gọn nhẹ', 'Film Simulation Dial', 'AF cải tiến'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '125-12800', shutterSpeed: '1/4000s', focusSystem: 'Intelligent Hybrid AF', videoRes: '4K 60p', weight: '378g', dimensions: '118 x 82 x 46 mm', battery: 'NP-W126S', storage: 'SD UHS-I', mount: 'Fujifilm X' }
  },
  {
    id: 'f6',
    name: 'Fujifilm X-H2',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 43900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2022/0915/ar/fujifilm-x-h2.jpg',
    sensor: SensorType.APS_C,
    resolution: '40.2MP',
    releaseYear: 2022,
    description: 'Flagship độ phân giải cao. Quay 8K, Pixel Shift 160MP.',
    features: ['Quay 8K 30p', 'Pixel Shift 160MP', 'CFexpress Type B', 'Quạt tản nhiệt rời'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '125-12800', shutterSpeed: '1/8000s', focusSystem: 'Hybrid AF', videoRes: '8K 30p', weight: '660g', dimensions: '136 x 92 x 84 mm', battery: 'NP-W235', storage: 'CFexpress B + SD', mount: 'Fujifilm X' }
  },
  {
    id: 'f7',
    name: 'Fujifilm X half (Đen)',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 15990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0828/ar/fujifilm-x-half-den-qua-33.jpg',
    sensor: SensorType.APS_C,
    resolution: '24MP',
    releaseYear: 2024,
    description: 'Máy ảnh Half-frame kỹ thuật số độc đáo. Chụp gấp đôi số lượng ảnh, phong cách dọc.',
    features: ['Cảm biến Half-frame crop', 'Thiết kế dọc', 'Tiết kiệm dung lượng', 'Bộ lọc màu retro'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '200-12800', shutterSpeed: '1/4000s', focusSystem: 'Contrast AF', videoRes: '1080p', weight: '280g', dimensions: '100 x 70 x 30 mm', battery: 'Internal', storage: 'MicroSD', mount: 'Fixed Lens' }
  },
  {
    id: 'f8',
    name: 'Fujifilm X-S20 + Kit XC 15-45mm',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 31500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2023/0528/ar/fujifilm-x-s20-1.jpg',
    sensor: SensorType.APS_C,
    resolution: '26.1MP',
    releaseYear: 2023,
    description: 'Bộ Kit khởi đầu tuyệt vời. X-S20 mạnh mẽ kèm lens XC nhỏ gọn.',
    features: ['Pin lớn', 'Quay Vlog đỉnh', 'Lens kit nhỏ gọn', 'Màu phim đẹp'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '160-12800', shutterSpeed: '1/4000s', focusSystem: 'AI AF', videoRes: '6.2K 30p', weight: '491g', dimensions: '127 x 85 x 65 mm', battery: 'NP-W235', storage: 'SD UHS-II', mount: 'Fujifilm X' }
  },
  {
    id: 'f9',
    name: 'Fujifilm X100VI - Màu Bạc',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 42990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2024/0221/ar/fujifilm-x100vi-9.jpg',
    sensor: SensorType.APS_C,
    resolution: '40.2MP',
    releaseYear: 2024,
    description: 'Chiếc máy ảnh compact được săn đón nhất thế giới. Giờ đây đã có chống rung IBIS.',
    features: ['Ống kính 23mm F2 II', 'IBIS 6-stop', 'Cảm biến 40MP', 'ND filter tích hợp'],
    isBestSeller: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '125-12800', shutterSpeed: '1/4000s (Lá)', focusSystem: 'AI AF', videoRes: '6.2K 30p', weight: '521g', dimensions: '128 x 74 x 55 mm', battery: 'NP-W126S', storage: 'SD UHS-II', mount: 'Fixed' }
  },
  {
    id: 'f10',
    name: 'Fujifilm X-T50 (Kèm 16-50mm)',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 38500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2024/0518/ar/fujifilm-x-t50-den-4.jpg',
    sensor: SensorType.APS_C,
    resolution: '40.2MP',
    releaseYear: 2024,
    description: 'Máy ảnh đầu tiên có vòng xoay giả lập màu Film Simulation Dial.',
    features: ['Film Simulation Dial', 'Cảm biến 40MP', 'IBIS 7-stop', 'Kit lens mới sắc nét'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '125-12800', shutterSpeed: '1/4000s', focusSystem: 'AI AF', videoRes: '6.2K 30p', weight: '438g', dimensions: '123 x 84 x 48 mm', battery: 'NP-W126S', storage: 'SD UHS-II', mount: 'Fujifilm X' }
  },
  {
    id: 'f11',
    name: 'Fujifilm X-S20 + XF 16-50mm',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 35990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2023/0528/ar/fujifilm-x-s20-1.jpg',
    sensor: SensorType.APS_C,
    resolution: '26.1MP',
    releaseYear: 2023,
    description: 'Combo nâng cao với lens kit XF mới khẩu lớn hơn, zoom trong.',
    features: ['Lens XF cao cấp', 'Zoom trong không thò thụt', 'Hiệu suất quay phim tốt', 'Cầm nắm thoải mái'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '160-12800', shutterSpeed: '1/4000s', focusSystem: 'AI AF', videoRes: '6.2K 30p', weight: '491g', dimensions: '127 x 85 x 65 mm', battery: 'NP-W235', storage: 'SD UHS-II', mount: 'Fujifilm X' }
  },
  {
    id: 'f12',
    name: 'Fujifilm GFX 50S II + 35-70mm',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 89900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2021/0910/ar/fujifilm-gfx-50s-ii-1.jpg',
    sensor: SensorType.MEDIUM_FORMAT,
    resolution: '51.4MP',
    releaseYear: 2021,
    description: 'Nhập môn Medium Format. Cảm biến lớn gấp 1.7 lần Full-frame cho độ nổi khối tuyệt vời.',
    features: ['Cảm biến Medium Format', 'IBIS 6.5-stop', 'Pixel Shift 200MP', 'Giá dễ tiếp cận'],
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '100-12800', shutterSpeed: '1/4000s', focusSystem: 'Contrast AF', videoRes: 'Full HD', weight: '900g', dimensions: '150 x 104 x 87 mm', battery: 'NP-W235', storage: '2x SD UHS-II', mount: 'Fujifilm G' }
  },
  {
    id: 'f13',
    name: 'Fujifilm X-T30 III + XC 13-33mm',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 26900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1121/ar/fujifilm-xt30-iii-kit-13-33mm-charcoal-qua-33.jpg',
    sensor: SensorType.APS_C,
    resolution: '40MP',
    releaseYear: 2024,
    description: 'Phiên bản Charcoal sang trọng đi kèm lens góc rộng mới.',
    features: ['Màu Charcoal đặc biệt', 'Lens góc rộng', 'Cảm biến 40MP', 'Nhỏ gọn'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '125-12800', shutterSpeed: '1/4000s', focusSystem: 'Hybrid AF', videoRes: '4K 60p', weight: '378g', dimensions: '118 x 82 x 46 mm', battery: 'NP-W126S', storage: 'SD UHS-I', mount: 'Fujifilm X' }
  },
  {
    id: 'f14',
    name: 'Fujifilm X-Pro 4',
    brand: Brand.FUJIFILM,
    category: Category.CAMERA,
    price: 49990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham-2019/may-anh-moi/fujifilm/x-pro3/fujifilm-x-pro3.jpg',
    sensor: SensorType.APS_C,
    resolution: '40MP',
    releaseYear: 2024,
    description: 'Nhiếp ảnh đường phố thuần túy. Kính ngắm lai Hybrid Viewfinder độc đáo.',
    features: ['Hybrid OVF/EVF', 'Màn hình ẩn', 'Vỏ Titan bền bỉ', 'Cảm biến 40MP'],
    isNew: true,
    videoUrl: MOCK_VIDEO_URL,
    specs: { iso: '125-12800', shutterSpeed: '1/8000s', focusSystem: 'AI AF', videoRes: '4K 60p', weight: '497g', dimensions: '140 x 82 x 46 mm', battery: 'NP-W126S', storage: '2x SD UHS-II', mount: 'Fujifilm X' }
  },
  // --- LENSES ---
  // Canon Lenses
  {
    id: 'l1',
    name: 'Canon RF 45mm F/1.2 STM',
    brand: Brand.CANON,
    category: Category.LENS,
    price: 15990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1106/ar/canon-rf-45mm-f1-2-stm-2.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2024,
    description: 'Tiêu cự chuẩn đời thường với khẩu độ siêu lớn F1.2.',
    features: ['Khẩu độ F1.2', 'Motor STM', 'Nhỏ gọn', 'Bokeh đẹp'],
    specs: { mount: 'Canon RF', weight: '400g', dimensions: '70x80mm', focusSystem: 'STM' }
  },
  {
    id: 'l2',
    name: 'Canon RF 16-28mm f/2.8 IS STM',
    brand: Brand.CANON,
    category: Category.LENS,
    price: 18500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0124/ar/rf-16-28mm-f2-8-is-stm-1.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2023,
    description: 'Lens zoom góc siêu rộng khẩu lớn giá tốt cho vlog và phong cảnh.',
    features: ['Góc rộng 16mm', 'Khẩu F2.8', 'Chống rung IS', 'Nhỏ gọn'],
    specs: { mount: 'Canon RF', weight: '450g', dimensions: '75x90mm', focusSystem: 'STM' }
  },
  {
    id: 'l3',
    name: 'Sigma 56mm f/1.4 Canon RF',
    brand: Brand.SIGMA,
    category: Category.LENS,
    price: 9900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0219/ar/sigma-56-canon-rf.jpg',
    sensor: SensorType.APS_C,
    releaseYear: 2023,
    description: 'Vua chân dung cho Crop. Tiêu cự tương đương 85mm trên Full-frame.',
    features: ['F1.4 siêu sáng', 'Rất sắc nét', 'Dành cho RF Crop', 'Bokeh mịn'],
    specs: { mount: 'Canon RF-S', weight: '280g', dimensions: '66x59mm', focusSystem: 'Stepper Motor' }
  },
  {
    id: 'l4',
    name: 'Canon RF 70-200mm f/4L IS USM',
    brand: Brand.CANON,
    category: Category.LENS,
    price: 38900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2021/0728/pd/rf-70-200-f-4.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2020,
    description: 'Tele zoom L-series ngắn nhất và nhẹ nhất thế giới.',
    features: ['Siêu gọn nhẹ', 'Chất lượng dòng L', 'Chống rung 5-stop', 'Nano USM kép'],
    specs: { mount: 'Canon RF', weight: '695g', dimensions: '83x119mm', focusSystem: 'Dual Nano USM' }
  },
  // Viltrox Lenses
  {
    id: 'l5',
    name: 'Viltrox AF 85mm F/1.4 PRO Z',
    brand: Brand.VILTROX,
    category: Category.LENS,
    price: 13500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0617/ar/af-85mm-f1-4-pro-fe-1.png',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2023,
    description: 'Dòng PRO cao cấp nhất của Viltrox. Chất lượng quang học vượt trội.',
    features: ['Dòng PRO', 'Khẩu F1.4', 'Weather Sealed', 'Clickless Aperture'],
    specs: { mount: 'Nikon Z', weight: '800g', dimensions: '87x100mm', focusSystem: 'STM' }
  },
  {
    id: 'l6',
    name: 'Viltrox AF 50mm f/1.4 FE',
    brand: Brand.VILTROX,
    category: Category.LENS,
    price: 11900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1021/ar/viltrox-af-50mm-f1-4-fe-1.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2021,
    description: 'Tiêu cự chuẩn với khẩu độ lớn. Đối thủ sừng sỏ của các lens chính hãng.',
    features: ['Khẩu F1.4', 'Build kim loại', 'Vòng khẩu độ', 'AF nhanh'],
    specs: { mount: 'Sony E', weight: '550g', dimensions: '75x88mm', focusSystem: 'STM' }
  },
  {
    id: 'l7',
    name: 'Viltrox AF 50mm f/1.8 FE',
    brand: Brand.VILTROX,
    category: Category.LENS,
    price: 6500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2024/0104/ar/af-50mm-f-1-8-fe-1.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2019,
    description: 'Giải pháp ngon bổ rẻ cho tiêu cự 50mm trên Sony Full-frame.',
    features: ['Giá rẻ', 'Nhẹ', 'AF tốt', 'Sharpness ổn'],
    specs: { mount: 'Sony E', weight: '340g', dimensions: '70x80mm', focusSystem: 'STM' }
  },
  {
    id: 'l8',
    name: 'Viltrox AF 16mm f/1.8 FE',
    brand: Brand.VILTROX,
    category: Category.LENS,
    price: 10900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2024/0102/ar/af-16mm-f-1-8-fe-for-sony-e-1.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2023,
    description: 'Góc siêu rộng khẩu lớn F1.8 hiếm có. Lý tưởng cho thiên văn và phong cảnh.',
    features: ['Góc 16mm F1.8', 'Màn hình LCD', 'Click switch', 'Ít méo'],
    specs: { mount: 'Sony E', weight: '550g', dimensions: '85x103mm', focusSystem: 'STM' }
  },
  // Nikon Lenses
  {
    id: 'l9',
    name: 'Nikon DX 16-50mm F/2.8 VR',
    brand: Brand.NIKON,
    category: Category.LENS,
    price: 8500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1021/ar/nikon-dx-16-50mm-f2-8-vr-1.jpg',
    sensor: SensorType.APS_C,
    releaseYear: 2023,
    description: 'Zoom chuẩn khẩu lớn hiếm hoi cho crop Nikon Z.',
    features: ['Khẩu F2.8 toàn dải', 'Chống rung VR', 'Nhỏ gọn', 'Lấy nét gần'],
    specs: { mount: 'Nikon Z DX', weight: '290g', dimensions: '70x65mm', focusSystem: 'STM' }
  },
  {
    id: 'l10',
    name: 'Nikon Z 50mm f/1.4',
    brand: Brand.NIKON,
    category: Category.LENS,
    price: 13500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2024/0911/ar/nikon-z-50mm-1-4.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2024,
    description: 'Phiên bản khẩu lớn giá tốt hơn dòng S-Line.',
    features: ['Khẩu F1.4', 'Mềm mại', 'Nhỏ hơn bản 1.8 S', 'Giá tốt'],
    specs: { mount: 'Nikon Z', weight: '420g', dimensions: '74x86mm', focusSystem: 'STM' }
  },
  {
    id: 'l11',
    name: 'Nikon Z 24-70mm f/2.8 S II',
    brand: Brand.NIKON,
    category: Category.LENS,
    price: 52000000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0823/ar/nikon-z-24-70mm-f2-8-s-ii-1.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2024,
    description: 'Lens zoom đa dụng tốt nhất hệ Nikon Z. Độ nét từ tâm ra rìa.',
    features: ['Dòng S-Line cao cấp', 'Khẩu F2.8', 'Lớp phủ ARNEO', 'Màn hình OLED'],
    specs: { mount: 'Nikon Z', weight: '805g', dimensions: '89x126mm', focusSystem: 'Multi-Focus' }
  },
  {
    id: 'l12',
    name: 'Nikon DX MC 35mm F/1.7',
    brand: Brand.NIKON,
    category: Category.LENS,
    price: 6500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1021/ar/nikon-dx-mc-35mm-f1-7-1.jpg',
    sensor: SensorType.APS_C,
    releaseYear: 2024,
    description: 'Lens Macro giá rẻ cho hệ máy Crop Nikon.',
    features: ['Chụp Macro', 'Tiêu cự chuẩn', 'Nhỏ gọn', 'Giá rẻ'],
    specs: { mount: 'Nikon Z DX', weight: '200g', dimensions: 'Compact', focusSystem: 'STM' }
  },
  // Sony Lenses
  {
    id: 'l13',
    name: 'Sony FE 24-70mm F2.8 GM II',
    brand: Brand.SONY,
    category: Category.LENS,
    price: 49990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2022/0428/ar/sony-fe-24-70-gm-ii-3.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2022,
    description: 'G Master thế hệ 2. Nhỏ hơn, nhẹ hơn, nhanh hơn và nét hơn.',
    features: ['G Master đỉnh cao', 'Nhẹ nhất phân khúc', '4 motor XD Linear', 'Vòng chỉnh khẩu'],
    specs: { mount: 'Sony E', weight: '695g', dimensions: '87x119mm', focusSystem: '4x XD Linear' }
  },
  {
    id: 'l14',
    name: 'Sony FE 50mm f/1.2 GM',
    brand: Brand.SONY,
    category: Category.LENS,
    price: 45990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2021/0318/ar/sony-fe-50-1-2-gm.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2021,
    description: 'Tuyệt tác tiêu cự 50mm. Độ mở F1.2 cho bokeh siêu thực.',
    features: ['Khẩu F1.2 cực lớn', 'Kích thước gọn gàng', 'Bokeh G Master', 'AF cực nhanh'],
    specs: { mount: 'Sony E', weight: '778g', dimensions: '87x108mm', focusSystem: '4x XD Linear' }
  },
  {
    id: 'l15',
    name: 'Sony E PZ 18-105mm F4 G OSS',
    brand: Brand.SONY,
    category: Category.LENS,
    price: 11990000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham/ong-kinh-may-anh/sony/sony-18-105g/lens-18-105mm-sony.jpg',
    sensor: SensorType.APS_C,
    releaseYear: 2013,
    description: 'Lens zoom điện quốc dân cho người quay phim Sony.',
    features: ['Power Zoom', 'Khẩu F4', 'G Lens', 'Internal Zoom'],
    specs: { mount: 'Sony E', weight: '427g', dimensions: '78x110mm', focusSystem: 'Linear' }
  },
  {
    id: 'l16',
    name: 'Sony FE 85mm F1.8',
    brand: Brand.SONY,
    category: Category.LENS,
    price: 11500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham/ong-kinh-may-anh/sony/sony-fe-85-f1-8/ong-kinh-sony-fe-85mm.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2017,
    description: 'Lens chân dung ngon bổ rẻ nhất của Sony.',
    features: ['Sắc nét', 'Lấy nét nhanh', 'Nhỏ nhẹ', 'Nút giữ nét'],
    specs: { mount: 'Sony E', weight: '371g', dimensions: '78x82mm', focusSystem: 'Double Linear' }
  },
  // Sigma Lenses
  {
    id: 'l17',
    name: 'Sigma 28-105mm f/2.8 DG DN',
    brand: Brand.SIGMA,
    category: Category.LENS,
    price: 36900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2024/0918/ar/sigma-28-105-sony.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2024,
    description: 'Lens zoom đa dụng khẩu độ lớn F2.8 đầu tiên trên thế giới đạt tiêu cự 105mm (L-Mount).',
    features: ['Dải zoom độc đáo', 'Khẩu F2.8 toàn dải', 'Dòng Art cao cấp', 'Nhẹ hơn mong đợi'],
    specs: { mount: 'L-Mount', weight: '995g', dimensions: '88x158mm', focusSystem: 'HLA' }
  },
  {
    id: 'l18',
    name: 'Sigma 28-105mm f/2.8 DG DN (E-mount)',
    brand: Brand.SIGMA,
    category: Category.LENS,
    price: 36900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2024/0918/ar/sigma-28-105-sony.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2024,
    description: 'Phiên bản ngàm Sony E của siêu phẩm zoom khẩu lớn.',
    features: ['Dải zoom độc đáo', 'Khẩu F2.8 toàn dải', 'Dòng Art cao cấp', 'Nhẹ hơn mong đợi'],
    specs: { mount: 'Sony E', weight: '995g', dimensions: '88x158mm', focusSystem: 'HLA' }
  },
  {
    id: 'l19',
    name: 'Sigma 30mm f/1.4 DC DN (Canon)',
    brand: Brand.SIGMA,
    category: Category.LENS,
    price: 7500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1111/pd/dd.jpg',
    sensor: SensorType.APS_C,
    releaseYear: 2023,
    description: 'Lens Prime tiêu chuẩn khẩu lớn cho hệ Canon RF Crop.',
    features: ['Khẩu F1.4', 'Tiêu cự tương đương 48mm', 'Contemporary', 'Gọn nhẹ'],
    specs: { mount: 'Canon RF-S', weight: '265g', dimensions: '65x73mm', focusSystem: 'Stepper' }
  },
  // Fujifilm Lenses
  {
    id: 'l21',
    name: 'Fujifilm XF 16-55mm F2.8 II',
    brand: Brand.FUJIFILM,
    category: Category.LENS,
    price: 28500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2024/1018/ar/xf-16-55mm-f2-8-r-lm-wr-ii-1.jpg',
    sensor: SensorType.APS_C,
    releaseYear: 2024,
    description: 'Bản nâng cấp của lens zoom tiêu chuẩn tốt nhất hệ X. Nhẹ hơn 37%.',
    features: ['Nhẹ hơn bản cũ', 'Vòng chỉnh khẩu clickless', 'AF nhanh hơn', 'Weather Sealed'],
    specs: { mount: 'Fujifilm X', weight: '410g', dimensions: '78x95mm', focusSystem: 'Linear Motor' }
  },
  {
    id: 'l22',
    name: 'Fujifilm XF 10-24mm f/4 R OIS WR II',
    brand: Brand.FUJIFILM,
    category: Category.LENS,
    price: 23500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0322/ar/xf-10-24mm-f4-r-ois-wr-ii-2.jpg',
    sensor: SensorType.APS_C,
    releaseYear: 2021,
    description: 'Góc siêu rộng cho phong cảnh và kiến trúc. Có chống rung OIS.',
    features: ['Góc siêu rộng', 'Có OIS', 'Weather Resistant', 'Vòng khẩu độ'],
    specs: { mount: 'Fujifilm X', weight: '385g', dimensions: '78x87mm', focusSystem: 'Stepper' }
  },
  {
    id: 'l23',
    name: 'Fujifilm XF 50-140mm F2.8 OIS WR',
    brand: Brand.FUJIFILM,
    category: Category.LENS,
    price: 32900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham-2019/ong-kinh-moi/fujifilm/fuji-50-140mm/fuji-50-140.jpg',
    sensor: SensorType.APS_C,
    releaseYear: 2014,
    description: 'Tele zoom chuyên nghiệp tương đương 70-200mm trên Fullframe.',
    features: ['Ba motor Linear', 'OIS 5-stop', 'Lớp phủ Nano-GI', 'Build tank'],
    specs: { mount: 'Fujifilm X', weight: '995g', dimensions: '83x176mm', focusSystem: 'Triple Linear' }
  },
  {
    id: 'l24',
    name: 'Fujifilm XF 50mm f/2 R WR',
    brand: Brand.FUJIFILM,
    category: Category.LENS,
    price: 10500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2023/0805/ar/fujifilm-xf-50mm-f2r-wr-silver-2.jpg',
    sensor: SensorType.APS_C,
    releaseYear: 2017,
    description: 'Lens chân dung nhỏ gọn dòng "Fujicron". Lấy nét cực nhanh.',
    features: ['Nhỏ gọn', 'WR chống chịu thời tiết', 'AF siêu tốc', 'Màu bạc/đen'],
    specs: { mount: 'Fujifilm X', weight: '200g', dimensions: '60x59mm', focusSystem: 'Stepper' }
  },
  // Carl Zeiss
  {
    id: 'l25',
    name: 'Carl Zeiss Batis 85mm F1.8',
    brand: Brand.CARL_ZEISS,
    category: Category.LENS,
    price: 24500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham/ong-kinh-may-anh/carl-zeiss/batis-85mm/ong-kinh-zeiss-bati-85-f1-8.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2015,
    description: 'Chất màu Zeiss trứ danh với màn hình OLED hiển thị khoảng cách độc đáo.',
    features: ['Màu Zeiss T*', 'Màn hình OLED', 'Chống rung quang học', 'Thiết kế liền khối'],
    specs: { mount: 'Sony E', weight: '475g', dimensions: '81x92mm', focusSystem: 'Linear' }
  },
  {
    id: 'l26',
    name: 'Carl Zeiss Batis 40mm f/2 CF',
    brand: Brand.CARL_ZEISS,
    category: Category.LENS,
    price: 26900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham/ong-kinh-may-anh/carl-zeiss/batis-40mm/ong-kinh-batis-40mm-f2-cho-sony-e-mount-1.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2018,
    description: 'Close Focus (CF) cho phép chụp cận cảnh ấn tượng. Tiêu cự 40mm đa dụng.',
    features: ['Close Focus 24cm', 'Màn hình OLED', 'T* Coating', 'Nét ngay tại F2'],
    specs: { mount: 'Sony E', weight: '361g', dimensions: '91x93mm', focusSystem: 'Linear' }
  },
  {
    id: 'l27',
    name: 'Carl Zeiss Batis 25mm f/2',
    brand: Brand.CARL_ZEISS,
    category: Category.LENS,
    price: 22500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham/ong-kinh-may-anh/carl-zeiss/carl-zeiss-batis-25mm-f2-for-sony-emount-3.jpg',
    sensor: SensorType.FULL_FRAME,
    releaseYear: 2015,
    description: 'Góc rộng huyền thoại của Zeiss Batis.',
    features: ['Góc rộng 25mm', 'Distagon design', 'Màu sắc đậm đà', 'Nhẹ'],
    specs: { mount: 'Sony E', weight: '335g', dimensions: '81x78mm', focusSystem: 'Linear' }
  },
  {
    id: 'l28',
    name: 'Carl Zeiss Touit 32mm f/1.8',
    brand: Brand.CARL_ZEISS,
    category: Category.LENS,
    price: 15900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham/ong-kinh-may-anh/carl-zeiss/zeiss-touit-32mm-f-1-8.jpg',
    sensor: SensorType.APS_C,
    releaseYear: 2013,
    description: 'Lens chuẩn cho hệ Crop Sony/Fuji.',
    features: ['Planar design', 'T* Coating', 'Rất sắc nét', 'AF êm'],
    specs: { mount: 'Sony E / Fuji X', weight: '210g', dimensions: '65x58mm', focusSystem: 'DC Motor' }
  },
  // --- ACCESSORIES ---
  {
    id: 'a1',
    name: 'Flash Godox iT32 + Trigger X5S',
    brand: Brand.GODOX,
    category: Category.ACCESSORY,
    price: 3500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1115/ar/flash-godox-it32-kem-trigger-x5n-9.jpg',
    sensor: SensorType.NA,
    releaseYear: 2024,
    description: 'Combo đèn flash nhỏ gọn và trigger điều khiển từ xa cho Sony.',
    features: ['Nhỏ gọn hoài cổ', 'Kèm Trigger X5', 'Pin sạc lại', 'Hồi đèn nhanh'],
    specs: { mount: 'Hotshoe Sony', weight: '150g', dimensions: 'Mini', focusSystem: 'N/A' }
  },
  {
    id: 'a2',
    name: 'Flash Godox iT32 + Trigger X5O',
    brand: Brand.GODOX,
    category: Category.ACCESSORY,
    price: 3500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1115/ar/flash-godox-it32-kem-trigger-x5n-7.jpg',
    sensor: SensorType.NA,
    releaseYear: 2024,
    description: 'Combo đèn flash nhỏ gọn cho hệ máy Olympus/Panasonic/Leica.',
    features: ['Tương thích M43', 'Kèm Trigger', 'Thiết kế Retro', 'Màn hình cảm ứng'],
    specs: { mount: 'M4/3 Hotshoe', weight: '150g', dimensions: 'Mini', focusSystem: 'N/A' }
  },
  {
    id: 'a3',
    name: 'Flash Godox V1 (Sony)',
    brand: Brand.GODOX,
    category: Category.ACCESSORY,
    price: 5200000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham/phu-kien-may-anh/den-flash-led/godox-v1/flash-godox-v1.jpg',
    sensor: SensorType.NA,
    releaseYear: 2019,
    description: 'Đèn Flash đầu tròn cho ánh sáng mềm mại tự nhiên.',
    features: ['Đầu tròn Fresnel', 'Pin Lithium Li-ion', 'Hỗ trợ phụ kiện nam châm', 'TTL/HSS'],
    specs: { mount: 'Sony MI Shoe', weight: '530g', dimensions: '76x93x197mm', focusSystem: 'N/A' }
  },
  {
    id: 'a4',
    name: 'Flash Godox iT30Pro N TTL',
    brand: Brand.GODOX,
    category: Category.ACCESSORY,
    price: 2800000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0618/ar/it30pro-11.jpg',
    sensor: SensorType.NA,
    releaseYear: 2023,
    description: 'Flash nhỏ gọn hỗ trợ TTL cho Nikon.',
    features: ['TTL Nikon', 'Nhỏ gọn', 'GN30', 'Hồi pin nhanh'],
    specs: { mount: 'Nikon Hotshoe', weight: '120g', dimensions: 'Compact', focusSystem: 'N/A' }
  },
  {
    id: 'a5',
    name: 'Đèn Led Neewer FS230B 230W',
    brand: Brand.NEEWER,
    category: Category.ACCESSORY,
    price: 4900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2024/0401/ar/fs230b-1.jpg',
    sensor: SensorType.NA,
    releaseYear: 2023,
    description: 'Đèn Studio công suất lớn, chỉnh nhiệt độ màu linh hoạt.',
    features: ['Công suất 230W', 'Bi-color 2700-6500K', 'Ngàm Bowens', 'Điều khiển qua App'],
    specs: { mount: 'Bowens', weight: '2.5kg', dimensions: 'Studio', focusSystem: 'N/A' }
  },
  {
    id: 'a6',
    name: 'Đèn LED Bơm Hơi Neewer GC21B',
    brand: Brand.NEEWER,
    category: Category.ACCESSORY,
    price: 1800000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0905/ar/led-neewer-gc21b-1.jpg',
    sensor: SensorType.NA,
    releaseYear: 2024,
    description: 'Giải pháp ánh sáng dã ngoại độc đáo, chống nước, gọn nhẹ.',
    features: ['Dạng bơm hơi', 'Chống nước IP66', 'Nam châm hít', 'Sạc USB-C'],
    specs: { mount: 'Nam châm', weight: '300g', dimensions: 'Inflatable', focusSystem: 'N/A' }
  },
  {
    id: 'a7',
    name: 'Flash Neewer Z2 Pro 76Ws',
    brand: Brand.NEEWER,
    category: Category.ACCESSORY,
    price: 3200000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/0808/ar/flash-neewer-z2-pro-1.jpeg',
    sensor: SensorType.NA,
    releaseYear: 2024,
    description: 'Đối thủ của Godox V1 với đầu tròn và pin Lithium.',
    features: ['Đầu tròn', 'Pin Lithium', 'TTL Sony', 'Modeling Light'],
    specs: { mount: 'Sony MI Shoe', weight: '500g', dimensions: 'Standard', focusSystem: 'N/A' }
  },
  {
    id: 'a8',
    name: 'Flash Canon Speedlite EL-10',
    brand: Brand.CANON,
    category: Category.ACCESSORY,
    price: 6500000,
    image: 'https://mayanh24h.com/upload/assets/thumb/2025/1104/ar/flash-canon-speedlite-el-10-1.jpg',
    sensor: SensorType.NA,
    releaseYear: 2024,
    description: 'Đèn flash tầm trung mới nhất cho hệ EOS R.',
    features: ['Chân kết nối đa năng', 'Điều khiển từ menu máy', 'Hồi đèn 1.5s', 'GN 40'],
    specs: { mount: 'Canon Multi-function', weight: '280g', dimensions: 'Compact', focusSystem: 'N/A' }
  },
  {
    id: 'a9',
    name: 'Flash Canon Speedlite 470EX-AI',
    brand: Brand.CANON,
    category: Category.ACCESSORY,
    price: 7900000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham/phu-kien-may-anh/den-flash-led/flash-canon-470ex/flash-canon-470ex.jpg',
    sensor: SensorType.NA,
    releaseYear: 2018,
    description: 'Đèn flash thông minh tự động xoay đầu đèn để bounce sáng.',
    features: ['AI Bounce tự động', 'GN 47', 'E-TTL II', 'Xoay linh hoạt'],
    specs: { mount: 'Canon', weight: '385g', dimensions: 'Standard', focusSystem: 'N/A' }
  },
  {
    id: 'a10',
    name: 'Chân Đèn Inox Light Stand 240cm',
    brand: Brand.NEEWER, // Generic but categorized
    category: Category.ACCESSORY,
    price: 850000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham/phu-kien-may-anh/chan-may-anh/chan-den-inox-240/chan-den-inox.jpg',
    sensor: SensorType.NA,
    releaseYear: 2020,
    description: 'Chân đèn C-Stand Inox chịu tải trọng lớn, bền bỉ.',
    features: ['Inox không gỉ', 'Cao 240cm', 'Có lò xo giảm chấn', 'Chịu tải 10kg'],
    specs: { mount: '1/4 screw', weight: '2kg', dimensions: '240cm', focusSystem: 'N/A' }
  },
  {
    id: 'a11',
    name: 'Bộ tản sáng Godox AK-R1 + Ngàm S-R1',
    brand: Brand.GODOX,
    category: Category.ACCESSORY,
    price: 1250000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham/phu-kien-may-anh/den-flash-led/godox-ak-r1/bo-tan-sang-godox-ak-r1.jpg',
    sensor: SensorType.NA,
    releaseYear: 2019,
    description: 'Bộ modifier nam châm cho đèn đầu tròn hoặc đèn thường (qua ngàm S-R1).',
    features: ['Nam châm hít', 'Gồm Dome, Snoot, Gel, Grid', 'Dễ sử dụng', 'Đa năng'],
    specs: { mount: 'Magnetic', weight: '200g', dimensions: 'Kit', focusSystem: 'N/A' }
  },
  {
    id: 'a12',
    name: 'Trigger Godox X2T for Sony',
    brand: Brand.GODOX,
    category: Category.ACCESSORY,
    price: 1100000,
    image: 'https://mayanh24h.com/upload/assets/thumb/catalog/san-pham/phu-kien-may-anh/den-flash-led/x2t/triger-godox-x2t-cho-sony.jpg',
    sensor: SensorType.NA,
    releaseYear: 2019,
    description: 'Bộ phát sóng điều khiển đèn flash từ xa. Có Bluetooth kết nối điện thoại.',
    features: ['Bluetooth App', 'TTL/HSS', 'Màn hình LCD', 'Hotshoe pass-through'],
    specs: { mount: 'Sony MI Shoe', weight: '90g', dimensions: '72x70x58mm', focusSystem: 'N/A' }
  }
];
